const mongoose = require('mongoose');
const { smartCareConn } = require('../config/db');

const PatientSchema = new mongoose.Schema({
  hisPid: String,
  mrn: String,
  createdTime: Date,
  admissionTime: Date,
  icuAdmissionTime: Date,
  icuDischargeTime: Date,
  admissionDiagnosis: String,
  clinicalDiagnosis: String,
  diagnosis: String,
  name: String,
  birthday: Date,
  age: mongoose.Schema.Types.Mixed,
  gender: String,
  hisBed: String,
  address: String,
  nation: String,
  allergicRecordList: Array,
  contactsName: String,
  hospitalTime: String,
  hospitalNo: String,
  bedNo: String,
  bedDoctor: String,
  department: String,
  deptName: String,
  wardName: String,
  admissionDoctor: String,
  attendingDoctor: String,
  admissionSource: String,
  dischargedType: String,
  dischargeType: String,
  dischargedDepartment: String,
  transferDept: String,
  bmiChangeHistoryList: Array,
}, { collection: 'patient', strict: false });

module.exports = smartCareConn.model('Patient', PatientSchema);
